#+TITLE: Dissertation Prospectus: Visual Imaginations of British Literature, 1880-1930
#+AUTHOR: Jonathan Reeve
#+DATE: 2018-1-29

I present a method for studying patterns in literary description which leverages recent developments in the computer science subfield of natural language processing. This is made possible by a model of literary production and reception which understands description as a set of cognitive processes: imaginations, as they are experienced by writers and readers. If we provisionally accept a model of a literary work as a sequence of words, read one at a time, and if we can assume that the materials of the writer---memory, sensory experience, intuition, imagination, other literary works, and so on---are rarely experienced so linearly, but in many simultaneous channels, we can deduce that writing effectuates a linearization of the writer's materials. This process happens in reverse, although not mirrored exactly, on the part of the reader: the reader reads words sequentially, but experiences all the work's literary elements in many channels. The reader /imagines/ the world described by the writing, thereby converting the word into mental /images/.

These images are not exclusively visual, and nor is imagination, despite its etymology–T. S. Eliot's "auditory imagination," for instance, refers to the reader's reconstruction of mental sounds. However, visual information, conveyed in prose, can be described well with this model, since visual properties tend to be more concrete and measurable than properties belonging to the other senses: /blue/, as a relatively static, synchronous experience, is more easily categorized than a dynamic, temporal auditory experience such as a /shriek/. When a writer begins with a mental image, that image—by definition if it is visual—has measurable properties: color, size, luminosity, and so on. The writer multiplexes or linearizes those properties into a sequence of words which approximate the experience. The process of approximation, I hypothesize, follows certain measurable patterns. 

The first of these patterns is selection: deciding which of an experience's sensory elements are necessary to convey it. As readers, we are well-practiced at providing missing information, or filling in the blanks. We do not need a complete description of something or someone, in order to imagine it. If we are reading a novel in which a character appears, we do not need to be told the material of a character's belt in order to picture him or her. Instead, descriptions often focus on anomalous aspects of what is described: what new information a reader would need in order to supplement their readerly imaginations. Sensory information likely to be shared by a writer and the writer's audience is often omitted, except where the writer calls attention to these effects, in what Viktor Shklovsky has called "estrangement" effects. The color of an orange is not described as orange, for we know it to be so, but it is described as green if the orange is green, and violates what the writer supposes are his audience's prior sensory conceptions.
 
The second pattern is categorization: those elements or properties are named according to their types. A hard gray jagged object is called a rock. Its color is called gray. This process is necessarily reductive, and the degree to which this reduction takes place is telling of the writer's descriptive style. The specificities of hue that Virginia Woolf uses in /Mrs Dalloway/---"grey-green," for instance---or the conspicuously vague descriptor "nocolored" from James Joyce's /Portrait of the Artist as a Young Man/, are both processes of reducing an experienced hue to a recognizable linguistic category. These categories are to some degree culturally conditioned, and conditioned by language conventions. Ludwig Wittgenstein, for instance, has remarked that in English, light red is termed /pink/ with much more regularity than the analogous values of light blue (cite:wittgenstein1978bemerkungen). Terms exist—cerulean, baby blue, and so on—but they are orders of magnitude less stable than the category /pink/. This phenomenon may be found in  other Western European languages, but it is not universally true of languages.

A third pattern is sequencing. The writer must decide the order in which to present an image's elements. If a novel's narrator consistently begins by describing the mountains in the distance of a place, instead of the trees in the foreground, or if another narrator describes the color of each person's hair before all else, these are serializing motions analogous to the kinetics of reading, that is, moving one's eye's across a page. When we view a painting in a gallery, we do not take it in all at once, but our eyes move across it selectively and sequentially—we "read" the painting. Similarly, we read faces and human bodies, according to certain patterns. Eye-tracking studies in cognitive psychology have identified some of these patterns. I will attempt to show that the same forces which govern eye motion patterns also govern the sequencing of visual imagery as linearized in literature.

These patterns model the process by which a writer's imagination encodes mental images into verbal imagery. Readers, then, using distinct but analogous imaginations, decode this imagery into other mental images. Whereas writers may omit shared sensory information, however, the reader introduces information drawn from memory: from prior sensory experience. A reader will not need to be told the color of a lime, unless it is an anomalously colored lime. Although limes are not the same color in the imaginations of every reader, the color of lime may be inferred within a high confidence interval by using patterns found in non-fiction, and in other literary texts. 

It need not be said that this is not a complete model of reading and writing. The processes I've begun to outline here do not always take place literally in literary works, of course, but metaphorically, as well, and according to the laws of other literary phenomena. The presence of the word "rock" in a text does not mean that rocks necessarily exist in the world depicted by the literary work: these rocks may be used as ways to describe other things. "Rock music" for instance, only has a metaphorical relation to actual rocks. I will attempt to control for these ambiguities with a number of disambiguation methods, which I will discuss in Chapter 3. Additionally, my focus on literary description, a relatively stable semantic field of convention—will help to mitigate this issue.

An even bigger problem for semantic stability is geographic variation: in Vietnam, oranges are usually green, for instance, so a phrase like "a green orange" might seem unusual to an American, but might contain extraneous information for a Vietnamese person. For this reason and others, I restrict the geographic range of my corpus to works published in, or written by those living in, Great Britain and Ireland. These limits are necessary not only to select for some degree of ecological regularity, but to foster morphological regularity of the language (words are easier to compare computationally if their orthographic conventions are similar), and relative socio-cultural predictability, as well. 
 
I provisionally choose the bounding dates 1880–1930 for this study for similarly practical reasons. For one, this period is well-studied (a survey of monograph titles shows this date range to be very popular among literary scholars), and so it provides for a more precise comparison with synchronic critical work than does, say, 1890–1940. The working lives of some of the period's most influential writers–Woolf, Joyce, and Pound, for instance—overlap significantly with this period, as well. Most importantly, however, I hypothesize that textual images—sequences of words that are either products of, or evocative of, mental images–are noticeably prominent in English-language British literature of the this period, roughly understood. They are not absent in prior or later literatures, of course, or literatures of other countries, but the most celebrated writers of this period discuss visual imaginations to a greater degree in their critical writings. At least one literary movement—the Imagism of the early twentieth century—was founded with explicit affinities toward the image-in-text. But this period exhibits even more imagisms, ones which predate this movement, and whose influences are felt long after. 

The texts I will study in this dissertation, then, will likely consist of British and Irish novels and poems published between the years 1880 and 1930. I plan to aggregate a number of corpora (that of the Modernist Journals Project, and that of the British Library, for instance), to generate a large corpus of between 70,000 and 200,000 texts. This corpus is by no means static, however, and I will likely change the parameters (geographic, temporal, and generic) as I go along, according to the quality of the available data.

This disseration will consist of six chapters: three which build theoretical and historical foundations, and three which consist of quantitative studies, each focusing on aspects of visual imaginations. The first chapter will build interdisciplinary theoretical backgrounds, drawing upon work in the cognitive sciences to supplement theories of writerly visual imagination in literary studies. The second will historicize the connective tissues between vision and the textual image, through a look at the critical and scientific writings of the period. The third will set the stage for the following chapters, explaining my quantitative methodology, and describing the experimental design. 

The three experimental chapters that follow are divided according to three aspects of vision: color (photopic vision), shape (scotopic vision), and space (spatial orientation, proprioception). Their subjects, as well, are aligned accordingly: descriptions of hue, descriptions of bodies, and descriptions of place. Each of the three experimental chapters will use a hybrid critical approach, combining close and "distant" reading. I will chiefly be using supervised machine-learning methods to computationally identify descriptive passages that fall under the above categories, and then analyzing their structure, affinities, topics, and changes over time. I believe these will give me insight into the workings of visual imaginations in this period of British literature.

The import for this method, for literary criticism, is immense and far-reaching. More than simply providing new data about this period in literary history, this method will constitute a new way of reading a text. Much in the same way that the movements of one's eyes may betray one's unexpressed desires (eyeing the door when one wants to leave a room, or eyeing an dish when one is hungry), programmatically enacting a visual imagination will help to reveal the desires of descriptive agents. Put differently, this set of experiments will constitute a new kind of computer-aided close reading. 

* Ch. 1: Cognitive Psychology and Reading Imaginations (Theory)

The first chapter will build the theoretical foundations I will employ in subsequent chapters. They are of necessity interdisciplinary, since many disciplines contribute to the study of vision. First, I will review the existing treatments of this topic in literary studies. I will pay particular attention to the critical trend of the early 1990s that gave weight to the related and overlapping concepts termed, on the writer's end "the written image," "iconology," and on the reader's end "textual envisioning," "the reader's eye," "the mind's eye," and "vivacity" (cite:collins1991reading; cite:mitchell2013iconology; cite:schwenger1999fantasm; cite:esrock1994reader; cite:wettlaufer2003mind; cite:scarry1995vivacity).

More recent criticism, as well, discusses this. The October 2018 issue of PMLA is a special issue on "Cultures of Reading," including an essay by Katherine Hayles which "addresses issues concerned with reading practices in a human-machine cognitive ecology" (cite:hayles2018human 1126). This will help to establish the relevance of this topic to the current critical conversations. From there, I will explore contemporary approaches to this area in the cognitive sciences: psychology of vision, linguistic philosophy of visual description, and phenomenology of vision. I am particularly interested in exploring experimental psychology of the reader's visual imagination of text: acts of reading, and acts of seeing. 

Eye movement studies, of which many have been conducted since the first in the 1960s, will help to proceduralize many of these theories of vision. If we can show that certain image types (landscapes, portraits) condition, however probabilistically, certain paths of reading that image, we might be able to use that path to explain the serializations of those images as they are translated, however selectively, into text. 

* Ch. 2: Fin-de-siècle Imagisms (Historicization)

The second chapter will contain a similar set of theoretical groundwork to the first, but will be more historically appropriate to the texts of the corpus. This chapter will build the case that functions of visual imaginations are instrumental to understanding this period of literature. I will provide a number of examples in which language mimics sight, and where writers of this period discuss their writing techniques in visual terms.

Here are a few examples. Ezra Pound, in addition to the work cited above, writes much about the centrality of the image to poetry. His attraction to the Chinese language, while somewhat misdirected, grows out of what he sees as the ideographic qualities of the Chinese written character. Pound's fascination with the textual image might be traced, at least in part, to the thought of the aesthetic philosopher T.E. Hulme, a figure well known in Pound's circle, and the addressee of his unsigned "document," which appears at the end of his anthology /Des Imagistes/, "To Hulme (T. E.) and Fitzgerald." Hulme has been called "the father of Imagism" and one for whom the image is "the key principle of [his] aesthetic," which "crystallizes the tensions between realism and nominalism, empirical detail and abstract thought" (cite:hughes1972imagism 9; cite:mead2015t 35). The Hulme scholar Henry Mead traces his fascination with the image to T. H. Huxley, who also taught and influenced H. G. Wells. Huxley, he continues, was in turn directly influenced by Henri Bergson, an influential thinker for modernist writers.

Virginia Woolf, in her essay, "The Cinema," notes that "in Shakespeare, as everybody knows, the most complex ideas, the most intense emotions form chains of images, through which we pass, however rapidly and completely they change, as up the loops and spirals of a twisting stair" (cite:woolf2009selected). Here as in Pound, ideas are constructed using chains of images. Visuality is central to Joseph Conrad's writing, as well. In the much-quoted preface to his novel, /The Nigger of the 'Narcissus,'/ he defines writing as "a single-minded attempt to render the highest kind of justice to the visible universe" (quoted in cite:levenson_genealogy_1986 1). His stated goal is "to make you hear, to make you feel ... before all, to make you /see/." Similarily, the writings of D. H. Lawrence, show a powerful visual imagination, one which has been the subject of at least one monograph: Keith Aldritt argues that Lawrence's training as a visual artist gave him an unusually robust dexterity with textual imagery (cite:alldritt1971visual vii). 

T. S. Eliot returns often to the image-in-text in his critical writings. He devotes a chaptes to visual halluicination in his early prose work /Knowledge and Experience/ (cite:eliot2014complete1 332). In his review of Ernest Fenollosa and Ezra Pound's /'Noh' or Accomplishment/, he may be found distinguishing between realism and the visual: 

#+BEGIN_QUOTE
"In general, we may say that the less “realistic” literature is, the more visual it must be. In reading /Pride and Prejudice/ or /The Wings of the Dove/ we hardly need to visualize at all; in reading Dante we need to visualize all the time. Dreams, to be real, must be seen." ( cite:eliot2014complete1 566). 
#+END_QUOTE

In the sciences, mental imagery became an important topic of study at the turn of the century. Sigmund Freud, in his influential /Interpretation of Dreams/ of 1899, notes the visual character of dreams, arguing that a factor responsible for translating "dream thoughts" into "dream content" is "the regard for presentability in the peculiar psychic material which the dream makes use of,---that is fitness for representation, for the most part by means of visual images" (freud1913interpretation 318).

One year earlier, Wilfred Lay's /Mental Imagery, Experimentally and Subjectively Considered/ tests the properties of mental imagery, remembered by readers of /Madame Bovary/. Lay classifies literary images as one of either /visual, auditory, olfactory, motor, thermal, tactile, organic,/ or /gustatory/. And in 1909, George Betts published a similarly influential study, /The Distribution and Functions of Mental Imagery/, which includes mental imagery questionnaires that are still in use sixty years later (cite:betts1909distribution; cite:sheehan1967shortened). Betts asks his subjects to think of their breakfast tables, and to sort in order of vividness a list of its attributes, such as the color of the tablecloth, or the shape of the spoons. His choices of attributes are not arbitrary, but are divided into the two categories, "as to outline, shape, and size," and "as to colors" (21). These categories correspond to scotopic and photopic vision, or to retinal rods and cones, and will correspond to chapters four and five of my dissertation. 

There are many more examples of these, which this chapter will discuss and synthesize.

* Ch. 3: Procedures, Formalisms (Method)

This chapter will discuss possible proceduralizations of the previous two chapters' observations. It will help to situate the method I will employ in the following chapters among similar critical endeavors. First, I will explain what I mean by visual-imaginary "operationalization," or "proceduralization": partial translation, or transmediation, of lexical data into sensory data, by serializing it as a set of instructions or a set of procedures. This is a way of formalizing (or serializing, verbalizing, mathematically encoding) some of the visual dimensions of literary texts.

Here, I will provide a demonstration of my technique. Turning to a random page in Joyce's /Dubliners/, I find these two sentences: "Mr O'Connor tore off a strip of the card and, lighting it, lit his cigarette. As he did so the flame lit up a leaf of dark glossy ivy in the lapel of his coat." Even without the context of these sentences, we can extrapolate a significant amount of information, if we can proceduralize a reader's visual imagination. 

Take the ivy, for example. First, we can extract photopic information about it. We know that it is probably a green, and a certain spectral range of green. From the modifier "dark" we know that this green is somewhat darker than usual, and from the modifier "glossy," we imagine that light may be reflecting off of this ivy, making it whiter than usual.

We may also extract scotopic information about the ivy: its size, shape, and borders. We already know that a leaf of ivy is restricted to a certain range of sizes, depending on its variety, and its maturity. We might assume that if the leaf fits into a lapel, that it's smaller than the lapel itself: one to two inches across, perhaps. We can infer a few things about the space, as well. The way the flame "lit up" this leaf, we may assume that the room or outdoor space they are in is dark. We might infer, then, that this scene takes place at night. 

This process of imagining—which I am here using in its etymological sense, to mean the conversion of textual abstractions into mental images—may be automated, if we can construct a machine which has access to visual assumptions about content words. Of course, these assumptions will always be subjective, and dependent on visual experience, but a reasonable starting-place might be constructed using the literary texts itself. For instance, we might gather color information about ivy by calculating the color words that appear within ten words of the word "ivy" in a large corpus of literary texts. (Although this has the problem that sheep are called "white sheep" significantly less than they are called "black sheep"—it is the exception that warrants the visual description.) 

Of course, one might criticize this reading of these two lines from /Dubliners/ as a naive reading that is ignoring the subtext of these lines, that the ivy is a symbolic representation of solidarity with the late Charles Stewart Parnell, as the title from which these lines are taken, "Ivy Day in the Committee Room," hints. But while the symbolic reading—one which might lead us from ivy to Parnell, to Home Rule, Irish Independence, British colonial history—takes us out of the realm of words, a superficial reading—one which devotes attention to the physical properties of the signifier itself—will not discard as by-products the raw materials with which symbols, metaphors, and other literary constructions are built. And if we automate these processes of information extraction, we could apply them to any number of texts. This has far-ranging consequences for our knowledge about these texts. We could use this measurement to track stylistic influence, generic evolution, or other literary-historical trends. 

This method has affinities with what Stephen Best and Sharon Marcus have called "surface reading," a method which does not dismiss its counterpart, "symptomatic reading," but calls for greater attention to "what is evident, perceptible, apprehensible in texts; what is neither hidden nor hiding; what, in the geometric sense, has length and breadth but no thickness, and therefore covers no depth" (cite:best2009surface 9). However, I will not draw conclusions merely with decontextualized surface /considerations,/ but I will use the presence of surface properties of a text /in aggregate/ as a means through which to understand new dimensions of the text. If a writer prefers to name green bodies (objects and so on) ten times as much as yellow, this could be revealing; similarly, if a narrator always describes a human body beginning at the feet, this could reveal the narrator's bodily preoccupations to such a degree that it could then inform a lens with which to reread the text.

I will situate my method among predecessors with similar methods: some works of Russian Formalists, especially Shklovsky—not their narratological work, but their work in categorizing sensory elements of folklore. Some aspects of literary structuralists, too, have methods akin to mine. More recent studies include a few ingenious but largely forgotten works of early computational literary analysis, like John B. Smith's work on imagery in /A Portrait of the Artist as a Young Man/ (cite:smith_imagery_1980). There are a even experiments in computer science that deal with operationalizing description, as well (cite:pizlo2014making). I will show how my method has benefited from these works, and how it departs from them. More recent work concerning the functions and properties of literary description will also prove helpful here. By literalizing literary description, I will get closer to understanding the function of description in novels and poetry. 

* Ch. 4: Descriptions of Color.

The first of my three experimental chapters deals with the perception and imagination of color: how color and hue are perceived and imagined by writers, encoded into sequences of language, and decoded or imagined by readers. The cognitive science I will build from here involves the psychology, physiology, and philosophy surrounding photopic vision: functions of retinal cones, and perceptions of hue. 

The experiments I will conduct here will be quantifications of colors and their literary expressions. First, I will quantify explicit color expressions: color words like "silver-gray" or "greenish." These alone will be revealing, I imagine, and could be used to compute color comparisons. Among the questions I'd be interested in answering here are: 

 - What are the favorite colors of each writer in the corpus? 
 - What writers display the most diversity of color words? How does this affect their descriptions?
 - What colors are most likely to begin a novel? Which colors are most likely to end it? Why?
 - What is the average color of a given novel? Do these correlate with setting, place of publication, writer, time of publication, or some other factor? Are chapters similarly bookended with colors, in this way? What about serially-published fiction?
  
Next, I will attempt to quantify implicit color mappings. The word /pear/, for instance, which ostensibly refers to the fruit, also refers to the color of the fruit. The DBPedia page for "Pear (color)," generated from Pantone, Plochere, and other color data sources, identifies four color mappings, which range from a light greenish-yellow to a deeper brownish-green: /pear sorbet/, /pear/, /medium winter pear/, and /winter pear/. I will be able to use data sources like these to map an occurrence of the word /pear/ to its machine-readable RGB or HSL values. More historically appropriate sources are widely available, as well: color manuals, made for artists and decorators, are abundant, both from the 1880-1930 period and from more recent times. Paint manufacturers, too, produced books of color names, often with poetic names like "exotic plum."
 
I might also be able to use image databases: since stock photo databases are so meticulously tagged, for instance, I could average the colors of these photos to create a reasonable word-to-color mapping. Not all of these mappings will be historically appropriate, of course, to the color mapping in the writer's visual imagination, but they will be more appropriate to contemporary readers' visual imaginations.

The existence of well-established linguistic categories of color, I suspect, will determine to a great degree their distributions in literature. That English seems to have a first-order concept for /pink/ as light red, but no analogous concept for blue, I hypothesize, will translate to greater incidence of pink in literature. If I could find the average fingerprint of English-language color categories, deviations from those might skew in some directions according to genre, topic, or the writer's linguistic background. Would Conrad's English-language writing, for instance, show traces of Polish, French, or the other languages with which he was acquainted? I also expect to find historical trends that correlate with certain material conditions: I imagine that colors in the range of purple, violet, and so on will show a spike in their literary representations in the decade following the synthesis of the dye around 1860. 

The result of this analysis will be a visualization---in the most literal possible sense---of the literary texts in my corpus. It will attempt to recreate /a/ visual imagination. Importantly, this will not be /the/ visual imagination, as if there is only one, but an aggregate imagination, one which is pieced together somewhat archaeologically from contemporaneous cultural data sources.

* Ch. 5: Descriptions of Shapes, Bodies, Objects.

Where the previous chapter focused on photopic aspects of vision, this chapter will deal with scotopc vision: that controlled by retinal rods, and responsible for night vision, the distinguishing of shapes, objects, and bodies. I use "bodies" here to refer to both discernible objects—as in "celestial bodies"—and to human bodies, as well. In the cognitive processes of vision, bodies are recognized as such by piecing together the edge-boundaries that compose them. The brain does not recognize instantaneously, but rather, the process follows a sequence which is neither arbitrary nor deterministic, yet obeys certain rules. Bodies are "read" (here again, I use a metaphor from the textual domain to describe the visual, instead of vice versa) following the movements of the eyes, which in turn are controlled by a host of subliminal factors. For inanimate objects, those factors might include utility (is it an object that can be used?), contrast (does it stand out from its background?). For human bodies, factors might include, on the part of the viewer, desire, social status, propriety, gender identity. These interpersonal factors, I hypothesize, will condition their descriptions of human bodies. How bodies are read—according to what virtual eye paths, with what fixations, and with what selectivity as to bodily segmentation—I imagine will be heavily conditioned by the social relationships of the describer and describee, even if these are fictional personae.

A greater epistemological question lurks here, of course: just what exactly /is/ an object? An object must first be perceived as discrete, before it is given a label. But to be perceived it must either be an island unto itself, with clear edges demarking it from its surroundings, and show some capacity for being displaced from its surroundings, or it must fall into a recognizable pre-determined category. As Eye movement tracking studies will be useful here: I hypothesize that eye movements that read an image of a human body will align with prose sequences describing bodies. Neurological studies have differentiated between patterns of recognition of faces and recognition of objects. Others have demonstrated patterns in object recognition, and differences between recognition of objects according to their edge-boundaries (cite:stockwell2012texture 107). 

The experiment I will conduct here will be a quantitative study of novels' and poems' descriptions of bodies, in both senses of the word. First, I will examine the positions of those categories of nouns which describe objects or discrete bodies, to determine how they are distributed in a text, and with respect to description. I will determine where and how they correlate with other literary phenomena, and what categories of objects these bodies fall into, according to well-established taxonomies such as those provided by thesauri. From there, I will determine the sequencing, segmenting, and categorizations of human bodies, as visually experienced and textually encoded. I am particularly interested in what I have called selection: how are certain parts of bodies (noses, cheeks, hair, hips, etc.) "read" by characters, narrators, or the speakers of poems? Why those parts, and not others? How are bodies selectively represented by their describers?
 
** Selected Working Bibliography
- 1974 - The time course of picture viewing. (cite:antes1974time)
- 2012 - When art moves the eyes: a behavioral and eye-tracking study (cite:massaro2012art)
- 2014 - Catching eyes: effects of social and nonsocial cues on attention capture (cite:bockler2014catching)
- 2018 - Using dual eye tracking to uncover personal gaze patterns during social interaction (cite:rogers2018)

* Ch. 6: Descriptions of Spaces: Rooms, Buildings, Cities.

The final experiment I will conduct will quantify properties of literary descriptions of space: rooms, buildings, cities, environments, and more. Spatial orientation is a important phenomenon to cognitive vision studies. As White et al. put it, "active vision involves a continual re-orienting of the line of sight with stimuli pertinent to current goals" (cite:White_2016 1). These goals will vary greatly according to space and social situation, but the important application of this observation of cognitive science is that there is rarely a purely aesthetic appreciation of space on the part of the describer, just as with the painter: the sequence with which the description reads or serializes a space reveals narratological and characterological forces.

Just as with the chapter on bodies above, I will measure the segmentation of landscapes, their serialization, and their distribution in time. Again, if distant mountains are described with much more attention than are closer features of the landscape, this distribution in narrative time reveals to some extent the preoccupations of the narrator, and it contributes to a certain visual tableau. Here again, eye tracking studies will be useful: the ways in which subjects are shown to move their eyes across landscape paintings, I imagine, will correlate with the ways in which landscapes are described. 

** Selected Working Bibliography

- 2000 - Of Other Spaces (cite:foucault2000other)
- 1992 - The Production of Space (cite:lefebvre1992production)
- 2003 - Moving Through Modernity: Space and Geography in Modernism (cite:thacker2003moving)
- 2016 - Neural Mechanisms of Saliency, Attention, and Orienting (cite:White_2016)
- 1996 - Visual landscape exploration as revealed by eye movement tracking (cite:de1996visual)

* Timeline

I will write the second half of this dissertation first, starting with chapters 4--6, and then writing chapters 1--3. This way, my description of method is descriptive, rather than prescriptive, and the theory I choose to scaffold my argument will be appropriate to the task of explaining my observations. 

 - September--October 2018: Create corpora, and related infrastructure.
 - November 2018--May 2019: Write Chapter 4 (Color).
 - May 2019: Submit color/description chapter for publication. 
 - May 2019--May 2020: Write Chapter 5 (Bodies). 
 - May 2020: Submit Chapter 5 for publication.
 - May 2020--November 2020: Write Chapter 6 (Spaces) and Chapter 1. 
 - November 2020: Submit Chapter 6 for publication.
 - November 2020--May 2021: Write remaining chapters.
 - May 2021: Defend dissertation.

* References
